name: Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  ci:
    uses: ./.github/workflows/run-nox.yml
  publish:
    name: Publish to TestPyPI
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: install flit
        run: pip install flit~=3.7
      - name: Build and publish
        run: flit publish
        env:
          FLIT_INDEX_URL: https://test.pypi.org/legacy/
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
