name: Check format, lint, type-check, run tests
on: [push, pull_request]
jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: excitedleigh/setup-nox@v2.1.0
      - run: nox -s check_format
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: excitedleigh/setup-nox@v2.1.0
      - run: nox -s lint
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: excitedleigh/setup-nox@v2.1.0
      - run: nox -s mypy
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        venv_version: ["3.8", "3.9", "3.10", "3.11", "pypy3"]
    steps:
      - uses: actions/checkout@v3
      - uses: excitedleigh/setup-nox@v2.1.0
      - name: Run tests
        run: nox -s test-${{ matrix.venv_version }}
